/*
 * GalleryComponent — the "/gallery" route
 *
 * Loads images from a gallery.json manifest (auto-generated by deploy.sh).
 * Each image filename encodes its metadata:
 *   <number>_<datetime>_<category>.jpg
 *   e.g. 0001_2026-02-25-10-30-00_water-heaters.jpg
 *
 * The component parses filenames to extract sort order, date, and category.
 * Categories are discovered dynamically — no hardcoded list needed.
 * Images load progressively: first batch on page load, more via "Load more".
 */
import { Component, OnInit, ChangeDetectorRef, inject } from '@angular/core';
import { CommonModule } from '@angular/common';

interface GalleryImage {
  filename: string;
  url: string;
  sortNumber: number;
  date: Date;
  category: string;
  categoryLabel: string;
}

/* How many images to show per batch */
const BATCH_SIZE = 9;

@Component({
  selector: 'app-gallery',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './gallery.component.html',
})
export class GalleryComponent implements OnInit {
  private cdr = inject(ChangeDetectorRef);
  allImages: GalleryImage[] = [];
  categories: string[] = [];
  activeCategory = 'All';
  visibleCount = BATCH_SIZE;
  loading = true;
  error = false;

  async ngOnInit(): Promise<void> {
    try {
      const response = await fetch('/gallery-photos/gallery.json');
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const filenames: string[] = await response.json();

      this.allImages = filenames
        .filter(f => f.endsWith('.jpg') || f.endsWith('.jpeg') || f.endsWith('.png') || f.endsWith('.webp'))
        .map(f => this.parseFilename(f))
        .sort((a, b) => a.sortNumber - b.sortNumber);

      const uniqueCats = [...new Set(this.allImages.map(img => img.categoryLabel))];
      this.categories = ['All', ...uniqueCats.sort()];
      this.loading = false;
      this.cdr.detectChanges();
    } catch {
      this.loading = false;
      this.error = true;
      this.cdr.detectChanges();
    }
  }

  /*
   * Parses a filename like "0001_2026-02-25-10-30-00_water-heaters.jpg"
   * into a structured GalleryImage object.
   */
  private parseFilename(filename: string): GalleryImage {
    const nameWithoutExt = filename.replace(/\.[^.]+$/, '');
    const parts = nameWithoutExt.split('_');

    /* parts[0] = "0001", parts[1] = "2026-02-25-10-30-00", parts[2+] = "water-heaters" */
    const sortNumber = parseInt(parts[0], 10) || 0;

    let date = new Date();
    if (parts[1]) {
      const [y, mo, d, h, mi, s] = parts[1].split('-').map(Number);
      date = new Date(y, (mo || 1) - 1, d || 1, h || 0, mi || 0, s || 0);
    }

    /* Category slug is everything after the second underscore (supports multi-word like "emergency-repairs") */
    const categorySlug = parts.slice(2).join('_') || 'uncategorized';

    /* Convert slug to display label: "water-heaters" → "Water Heaters" */
    const categoryLabel = categorySlug
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');

    return {
      filename,
      url: `/gallery-photos/${filename}`,
      sortNumber,
      date,
      category: categorySlug,
      categoryLabel,
    };
  }

  get filteredImages(): GalleryImage[] {
    if (this.activeCategory === 'All') {
      return this.allImages;
    }
    return this.allImages.filter(img => img.categoryLabel === this.activeCategory);
  }

  get visibleImages(): GalleryImage[] {
    return this.filteredImages.slice(0, this.visibleCount);
  }

  get hasMore(): boolean {
    return this.visibleCount < this.filteredImages.length;
  }

  setCategory(category: string): void {
    this.activeCategory = category;
    this.visibleCount = BATCH_SIZE;
  }

  loadMore(): void {
    this.visibleCount += BATCH_SIZE;
  }

  /* Lightbox state */
  selectedImage: GalleryImage | null = null;

  openLightbox(image: GalleryImage): void {
    this.selectedImage = image;
  }

  closeLightbox(): void {
    this.selectedImage = null;
  }

  /* Navigate to prev/next image within the filtered set */
  prevImage(): void {
    if (!this.selectedImage) return;
    const list = this.filteredImages;
    const idx = list.indexOf(this.selectedImage);
    this.selectedImage = list[(idx - 1 + list.length) % list.length];
  }

  nextImage(): void {
    if (!this.selectedImage) return;
    const list = this.filteredImages;
    const idx = list.indexOf(this.selectedImage);
    this.selectedImage = list[(idx + 1) % list.length];
  }
}
