export const DEFAULT_LOCATIONS: string[] = [
  'Burr Ridge, IL',
  'Des Plaines, IL',
  'Downers Grove, IL',
  'Elmhurst, IL',
  'Evanston, IL',
  'Glen Ellyn, IL',
  'Glenview, IL',
  'Hinsdale, IL',
  'La Grange, IL',
  'La Grange Park, IL',
  'Lombard, IL',
  'Naperville, IL',
  'Northbrook, IL',
  'Skokie, IL',
  'Villa Park, IL',
  'Western Springs, IL',
  'Westmont, IL',
  'Wheaton, IL',
  'Wilmette, IL',
  'Winnetka, IL',
];
